#!/bin/bash
model_engine="text-davinci-003"
key=$(sed 's/ //g' /data/data/com.termux/files/usr/bin/key.txt)
api_key="$key"
mensaje=$1
btn=Asis
todo () {	
if [[ $mensaje == "" ]];then
	echo "para usar el asistente escribe:"
	tput setaf 1;echo -n "         asis";tput setaf 10;echo '  "pregunta"'
else
	respuesta=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $api_key" https://api.openai.com/v1/engines/$model_engine/completions -d "{\"prompt\":\"$mensaje\",\"max_tokens\":1024,\"temperature\":0.5}" | jq -r '.choices[0].text' )
	if [[ $respuesta == "" ]] || [[ $respuesta == "null" ]];then
		tput setaf 1;echo "no hay conexion a internet o al servidor del bot"
		exit
	else
		tput setaf 1;echo -n "$btn:";tput setaf 10;echo -e "$respuesta"
	fi
fi
}

if [[ $btn = "Asis" ]];then                               todo                                      
else
	echo "Hubo un error, vuelve a instalar asis"
fi
